### ISSUE TITLE
Error at build

### ISSUE THREAD

**Issue by BenjaminHorn** [givanse/broccoli-babel-examples#3]
I try to build and run on Windows 7. After

```
npm install 
broccoli serve
```

I'm getting this error. 

```
Built with error:
Error: ENOENT, no such file or directory 'c:\babel\es6-website\tmp\funnel-input_base_path-dAZWvUeB.t
mp\0\browser-polyfill.js'
    at Error (native)
    at Object.fs.statSync (fs.js:801:18)
    at Object.copyDereferenceSync (c:\babel\es6-website\node_modules\broccoli-funnel\node_modules\sy
mlink-or-copy\node_modules\copy-dereference\index.js:13:21)
    at symlinkWindows (c:\babel\es6-website\node_modules\broccoli-funnel\node_modules\symlink-or-cop
y\index.js:92:13)
    at Function.symlinkOrCopySync (c:\babel\es6-website\node_modules\broccoli-funnel\node_modules\sy
mlink-or-copy\index.js:56:5)
    at Funnel._copy (c:\babel\es6-website\node_modules\broccoli-funnel\index.js:295:17)
    at Funnel.processFile (c:\babel\es6-website\node_modules\broccoli-funnel\index.js:286:8)
    at Funnel.processFilters (c:\babel\es6-website\node_modules\broccoli-funnel\index.js:197:12)
    at Funnel.build (c:\babel\es6-website\node_modules\broccoli-funnel\index.js:161:10)
    at c:\babel\es6-website\node_modules\broccoli-funnel\node_modules\broccoli-plugin\read_compat.js
:61:34
```

(The fruit example seems to work.)

**Comment by BenjaminHorn** [comment]
removing , `{browserPolyfill: true}`  from

``` javascript
// Transpile the source files
var appJs = babel('src', {browserPolyfill: true});
```

solves the problem, but then I get any empty page (only html) on http://localhost:4200/

**EDIT**

After updating "broccoli-babel-transpiler" to "5.4.5", I can use `{browserPolyfill: true}` but it still does not work, console error:

```
Uncaught ReferenceError: regeneratorRuntime is not defined
```

Here is how **my-app.js** looks after the build:

``` javascript
/*
  ES6 Generator

  In order to use Generators you must include the Babel polyfill. 
  https://babeljs.io/docs/learn-es6/#generators

  I can't really handle hex codes :p
*/
'use strict';

var marked0$0 = [hexRange].map(regeneratorRuntime.mark);
function hexRange(start, stop, step) {
  var i;
  return regeneratorRuntime.wrap(function hexRange$(context$1$0) {
    while (1) switch (context$1$0.prev = context$1$0.next) {
      case 0:
        i = start;

      case 1:
        if (!(i < stop)) {
          context$1$0.next = 7;
          break;
        }

        context$1$0.next = 4;
        return i;

      case 4:
        i += step;
        context$1$0.next = 1;
        break;

      case 7:
      case 'end':
        return context$1$0.stop();
    }
  }, marked0$0[0], this);
}

function printColors() {
  var content$ = $('#content');

  var _iteratorNormalCompletion = true;
  var _didIteratorError = false;
  var _iteratorError = undefined;

  try {
    for (var _iterator = hexRange(900, 999, 10)[Symbol.iterator](), _step; !(_iteratorNormalCompletion = (_step = _iterator.next()).done); _iteratorNormalCompletion = true) {
      var hex = _step.value;
      // contrived example
      var newDiv = $('<div>').attr('class', 'color').css({ 'background-color': '#' + hex }).append('hex code: #' + hex);
      content$.append(newDiv);
    }
  } catch (err) {
    _didIteratorError = true;
    _iteratorError = err;
  } finally {
    try {
      if (!_iteratorNormalCompletion && _iterator['return']) {
        _iterator['return']();
      }
    } finally {
      if (_didIteratorError) {
        throw _iteratorError;
      }
    }
  }
}

$(printColors);
'use strict';

function printInfo() {
  $('#info').append('<p>Minimal website example<br>' + 'with Broccoli and Babel.</p>');
}

$(printInfo);
```

**Comment by givanse** [comment]
I've confirmed the error with broccoli-babel-transpiler `5.4.5`.

Note that this repo **is not** broken. If you clone it and execute everything as told in the README, all the examples work. The error does not appear in `5.3.0`.

**Comment by givanse** [comment]
The change that caused this: https://github.com/babel/broccoli-babel-transpiler/commit/d923d95f93b54c86367dd5a43558f52459e3d185

follow up: https://github.com/babel/broccoli-babel-transpiler/issues/59
